allowBuilds:
  better-sqlite3: true
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@mkven/name-dictionaries@0.2.0'
  - '@types/node'
  - 'tsx'
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - simple-git-hooks
overrides:
  'axios@<1.15.2': '>=1.15.2'
  'vite@<7.3.2': '>=7.3.2'
